# Generated by Django 4.1.7 on 2023-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='event/%Y/%m/%d/', verbose_name='thumbnails')),
            ],
        ),
    ]
